import { chromium } from 'playwright';
import nodemailer from 'nodemailer';
import { prisma } from '../lib/prisma.js';
import path from 'path';
import fs from 'fs/promises';

const EXPORT_DIR = path.resolve('exports');

/**
 * Convert a takedown request template to PDF
 */
export async function generateTakedownPdf(takedownId: string): Promise<Buffer> {
  const takedown = await prisma.takedownRequest.findUniqueOrThrow({
    where: { id: takedownId },
    include: {
      detectedDomain: {
        include: { brand: { include: { organization: true } } },
      },
    },
  });

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {
      font-family: 'Helvetica Neue', Arial, sans-serif;
      max-width: 700px;
      margin: 40px auto;
      padding: 40px;
      color: #222;
      font-size: 14px;
      line-height: 1.7;
    }
    .header {
      border-bottom: 3px solid #1a56db;
      padding-bottom: 16px;
      margin-bottom: 32px;
    }
    .header h1 {
      color: #1a56db;
      font-size: 22px;
      margin: 0;
    }
    .header .org {
      color: #666;
      font-size: 13px;
      margin-top: 4px;
    }
    .meta {
      background: #f8f9fa;
      border-left: 4px solid #1a56db;
      padding: 12px 16px;
      margin: 24px 0;
      font-size: 13px;
    }
    .meta strong { color: #1a56db; }
    .content { white-space: pre-wrap; }
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #ddd;
      font-size: 11px;
      color: #999;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Takedown Request</h1>
    <div class="org">${takedown.detectedDomain.brand.organization.name}</div>
  </div>
  <div class="meta">
    <strong>Infringing Domain:</strong> ${takedown.detectedDomain.domain}<br>
    <strong>Protected Brand:</strong> ${takedown.detectedDomain.brand.name} (${takedown.detectedDomain.brand.domain})<br>
    <strong>Registrar:</strong> ${takedown.registrar}<br>
    <strong>Date:</strong> ${new Date().toISOString().split('T')[0]}<br>
    <strong>Status:</strong> ${takedown.status}
  </div>
  <div class="content">${escapeHtml(takedown.template)}</div>
  <div class="footer">
    Generated by BrandShield — ${new Date().toISOString()}
  </div>
</body>
</html>`;

  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle' });
    const pdf = await page.pdf({
      format: 'A4',
      margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' },
      printBackground: true,
    });
    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}

/**
 * Save PDF to disk and return path
 */
export async function saveTakedownPdf(takedownId: string): Promise<string> {
  await fs.mkdir(EXPORT_DIR, { recursive: true });
  const pdf = await generateTakedownPdf(takedownId);
  const filename = `takedown-${takedownId.slice(0, 8)}-${Date.now()}.pdf`;
  const filepath = path.join(EXPORT_DIR, filename);
  await fs.writeFile(filepath, pdf);
  return filepath;
}

/**
 * Send takedown request via email with PDF attachment
 */
export async function sendTakedownEmail(
  takedownId: string,
  recipientEmail: string,
): Promise<void> {
  const takedown = await prisma.takedownRequest.findUniqueOrThrow({
    where: { id: takedownId },
    include: {
      detectedDomain: {
        include: { brand: { include: { organization: true } } },
      },
    },
  });

  const pdf = await generateTakedownPdf(takedownId);

  const brand = takedown.detectedDomain.brand;

  // Use brand-specific SMTP if configured, otherwise fall back to env defaults
  const smtpConfig = brand.smtpHost
    ? {
        host: brand.smtpHost,
        port: brand.smtpPort || 587,
        secure: (brand.smtpPort || 587) === 465,
        auth: { user: brand.smtpUser || '', pass: brand.smtpPass || '' },
      }
    : {
        host: process.env.SMTP_HOST || 'smtp.gmail.com',
        port: Number(process.env.SMTP_PORT || 587),
        secure: false,
        auth: { user: process.env.SMTP_USER || '', pass: process.env.SMTP_PASS || '' },
      };

  const transporter = nodemailer.createTransport(smtpConfig);

  const senderEmail = brand.senderEmail || process.env.SMTP_FROM || process.env.SMTP_USER;
  const brandName = brand.name;
  const domain = takedown.detectedDomain.domain;

  await transporter.sendMail({
    from: senderEmail,
    to: recipientEmail,
    subject: `Takedown Request: ${domain} — Brand Infringement on ${brandName}`,
    text: takedown.template,
    attachments: [
      {
        filename: `takedown-${domain}.pdf`,
        content: pdf,
        contentType: 'application/pdf',
      },
    ],
  });

  // Update status
  await prisma.takedownRequest.update({
    where: { id: takedownId },
    data: { status: 'sent', sentAt: new Date() },
  });
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
